defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
    date_fmt: "%F"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    categories: "news"
    date_fmt: "%F"

exclude:
- README.md
- Gemfile
- Gemfile.lock
- new_post.sh
- setup.sh
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

name: JACK Audio Connection Kit
markdown: Kramdown
highlighter: rouge

url: "https://jackaudio.org"

organization:
  url: "https://github.com/jackaudio"

repository:
  branch: "master"
  url: "https://github.com/jackaudio/jackaudio.github.com"

# Slate theme settings, here only for the slate-theme page as example.
show_downloads: true
google_analytics:

# Overriding GH settings as demonstration.
# We don't rely on these ones but using our own above.
# See https://github.com/jekyll/github-metadata/blob/master/docs/site.github.md
github:
  is_project_page: true
  project_tagline: "Slate is a theme for GitHub Pages."
  repository_name: "Slate theme"
  repository_url:  "https://github.com/pages-themes/slate"
  tar_url:         "https://github.com/pages-themes/slate/tarball/master"
  zip_url:         "https://github.com/pages-themes/slate/zipball/master"
  owner_url:       "https://github.com/pages-themes"
  owner_name:      "pages-themes"
